[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
subly_solana_program = "C1gJtFGfd2Tt3omV6eWvezeofymZbp7RYj94Hg4drWq1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize-devnet = "yarn initialize-devnet"
register-services = "yarn register-subscription-services scripts/subscription-services.json"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
